wandb_version: 1

dataset:
  desc: null
  value: Shadoc-lowres
architecture:
  desc: null
  value: UNetWithoutAT
epochs:
  desc: null
  value: 50
learning_rate:
  desc: null
  value: 0.0001
batch_size:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713966406.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.16.6
      6: 4.39.3
      8:
      - 1
      - 5
      13: linux-x86_64
